### ISSUE TITLE
Question Sourcing

### ISSUE THREAD

**Issue by IOnlyShoot3s** [EricAndrechek/FermiQuestions#19]
The authors and then the links are not correct for some of the questions

**Comment by EricAndrechek** [comment]
Could you elaborate further? How it works right now (if it is working properly) is that it shows the source information for the previous question after you submit a guess, so the source info is for the last question, not the one currently showing.

**Comment by IOnlyShoot3s** [comment]
Oh oops I thought it was for the current question

**Comment by EricAndrechek** [comment]
Maybe the current question would make more sense... what do you think should I change it to that?

**Comment by IOnlyShoot3s** [comment]
I don't know how much work it would be but the best thing could be like to have "Previous question sourced..." and "Current question sourced...". If only one link is there then I guess just have it say "Previous" or "Current" so there's no confusion

**Comment by EricAndrechek** [comment]
Yeah that's a good idea and would help remove some ambiguity. I'm away from a computer for the next while but once I'm back to one I'll make that change. It's a pretty simple change to make.
