### ISSUE TITLE
Incorrect Question Answer

### ISSUE THREAD

**Issue by NathanielSchwartz** [EricAndrechek/FermiQuestions#23]
The question is 2^2^2^2. The exact answer is 65536. This would mean an order of magnitude of 5. The "correct" order of magnitude is 19728.

**Comment by EricAndrechek** [comment]
You're right in that the current answer is incorrect, not sure why that would be. I checked the source provided by @IOnlyShoot3s, which can be found [here](https://drive.google.com/drive/folders/14B7kBvOodk0_7ulRpUww1SaqxBrfjrnx) and it also says 19728. I am struggling to see how the test-makers could have come up with that number and am inclined to change it unless someone can explain why it may be that number.

**Comment by IOnlyShoot3s** [comment]
There are 5 2s, not 4

**Comment by EricAndrechek** [comment]
Haha yep, that explains it. Reading the question bank more carefully and it is indeed 5 2's. Now this answer makes sense: 
<img width="795" alt="image" src="https://user-images.githubusercontent.com/35144594/200686338-e6cd51b4-4117-49f1-962e-44d1290a0edb.png">

Closing and leaving it as is. Thanks for catching that @IOnlyShoot3s
