### ISSUE TITLE
Incorrect Answer

### ISSUE THREAD

**Issue by b3anbean** [EricAndrechek/FermiQuestions#25]
The answer to "How many hours elapse from one full moon to the next" is marked as 3, but it takes approximately 29.5 days for the moon to complete one full cycle: 29.5 * 24=708=7.08 * 10^2. Wouldn't the correct answer be 2?

**Comment by ahnoah** [comment]
> The answer to "How many hours elapse from one full moon to the next" is marked as 3, but it takes approximately 29.5 days for the moon to complete one full cycle: 29.5 * 24=708=7.08 * 10^2. Wouldn't the correct answer be 2?

3 is the correct answer for a value of 7.08 * 10^2. remember, when the first number of scientific notation is greater than or equal to 5, fermi rounds up.

**Comment by EricAndrechek** [comment]
@all-contributors add @ahnoah for maintenance
