### ISSUE TITLE
Units lacking

### ISSUE THREAD

**Issue by JohnEikenburg** [EricAndrechek/FermiQuestions#34]
This tool is cool!  Some of the questions lack units

**Comment by EricAndrechek** [comment]
Thank you! Yes, most of these questions and their answers were copied directly from Fermi questions from Science Olympiad tests, and many of those are lacking such units. It is a pretty time-consuming process to go through and update said questions and add units, but feel free to open issues or create pull requests to fix any specific ones you notice!
