### ISSUE TITLE
How many hours elapse from one full moon to the next? -- Incorrect answer

### ISSUE THREAD

**Issue by Ishaan4321** [EricAndrechek/FermiQuestions#36]
It says the answer is 3 (10^3), but the cycle between moons is 30 (29.5)  days, which, multiplied by 24 hours in a day is ~720, not 1,000 or above. The answer should be 2.

**Comment by TX1999-pro** [comment]
We refer to the rounding with the geometric mean.

You can use this tool to check: https://rechneronline.de/rounding/fermi.php

> "Fermi rounding uses the geometric mean of 1 and 10, which is the square root of 10, about 3.2. Therefore, it is rounded down up to 3 and rounded up from 4."

**Comment by EricAndrechek** [comment]
@all-contributors add @TX1999-pro for maintenance
