### ISSUE TITLE
The mass of the earth in tons? -- Incorrect answer

### ISSUE THREAD

**Issue by Ishaan4321** [EricAndrechek/FermiQuestions#37]
Says 22, should be 21. To convert between kg and tons, approximately divide by 907. Mass of earth: ~6*10^24 kg, so didvide by 907 and you get ~6.5*10^21.

**Comment by TX1999-pro** [comment]
According to Fermi Estimation, 6.51^21 is in the magnitude of 22 since log(6.51) = 0.814 > 0.5
