### ISSUE TITLE
Where are the questions sourced?

### ISSUE THREAD

**Issue by Haadi-Khan** [EricAndrechek/FermiQuestions#4]
I think it would to helpful to write locations where the questions come from. This would especially help when contributing to the repository and adding questions from invitationals, s as well as being able to easily know if duplicates exist.

Maybe a note in the README or a separate md file would be a good place to make the list?

**Comment by EricAndrechek** [comment]
Thanks for the suggestion! I agree this would add to the project, although unfortunately I compiled this original list several years ago and have no idea where I would begin in trying to locate the origins of all of these questions. Most of them came from practice tests that various invitationals made public, and some were from invitationals I had attended. Hunting down all those sources would be basically impossible at this point.

I could, however, make a new md file to help log where questions are sourced in the future. My question for you regarding this would then be how to structure that log. If we just listed line numbers and sources, deleting a question in the master list would cause all the line numbers to move around. If we wrote out the entire question, the log would get really long if someone dumped in all the questions from their invitational. I also would prefer to try and avoid modifying the JSON schema as then all the client code would need to be updated, and the web request size for the users would balloon, although this could also be cool for the user to have a link to click for each question to see its source. Let me know what you think a good approach would be, I am open to suggestions!

Also, regarding duplicates, my plan there was to kind of just CTRL+F for similar phrases in the existing question list and filter out duplicates before accepting merge requests. You have got me thinking about adding a Github action to do this for me now though...

**Comment by Haadi-Khan** [comment]
You could restructure the existing json so that it follows (sorry for bad formatting I'm on GH Mobile)

```json
{
  "og": [
    {"Ex. 1": 7},
    ...
   ],
  "mit": [
    ...
  ],
  ...
}
```

and so on. Converting the current json file over shouldn't be hard (either a sed command or a vim macro depending on how lazy you are). Updating the code to follow this format shouldn't be much trouble either.

This now means that making an md containing the list of invies should be pretty simple, since the line numbers are irrelevant.

As for duplicates, I assume you mean more akin to word for word duplicates. Multiple (even many) questions of a similar type definitely make sense for a training resource since it depicts the type of difficulty you could have.

This also opens you up to maybe making an option to pick a easier vs harder mode (further off goal but worth enough to think about) if you want to try to implement it based off "question type". Almost definitely overkill, but if you get bored enough...

Regardless, I'm intending on sharing this site around with as many people as I can, and I'll try to contribute whenever possible. Thank you for making this site

**Comment by EricAndrechek** [comment]
I agree reformatting the existing JSON isn't hard, it's more the frontend javascript I am concerned about. Wrapping questions in nested source keys would mean that the existing site breaks, and so somehow the existing cache would need to be invalidated. I will look into how much code would need to be rewritten, as right now I think it just runs through the object keys, and this would require some additional complexity. I am pretty busy right now with some other projects but I will look into this. 

Ha, I was just thinking about this sort of thing. Some sort of NLP to process how similar questions are, and then to additionally classify them into potential categories you could select. I think I'd need a bigger question bank to justify that, though, but maybe in the future!

I appreciate the support, and yeah pull requests are always appreciated! I will leave this open until I can address the source issue. Thanks again.

**Comment by EricAndrechek** [comment]
Alright, so I got caught thinking about all this and couldn't get my work done so I just quickly knocked this out instead. Now there are linked sources. Let me know what you think of that, and thanks again for the suggestion!

**Comment by EricAndrechek** [comment]
@all-contributors add @Haadi-Khan for ideas
