### ISSUE TITLE
Adding Questions

### ISSUE THREAD

**Issue by IOnlyShoot3s** [EricAndrechek/FermiQuestions#8]
If I wanted to, how would i be able to add questions myself or submit some to be added?

**Comment by EricAndrechek** [comment]
Thanks for your interest in adding some questions! I attempted to address this question [in the readme](https://github.com/EricAndrechek/FermiQuestions#adding-a-question), but I can understand that this may be a bit technical or confusing for people not familiar with Github, so I'll try to add some more info to help clear it up.

If any of the following instructions are too confusing, I would graciously accept new issues in which you pasted all the questions and answers you wanted to add along with your source(s) and I can add them for you. If you want to save me some time and effort, here is how:

To start, click on the [question-bank.json](https://github.com/EricAndrechek/FermiQuestions/blob/main/question-bank.json) file.
![image](https://user-images.githubusercontent.com/35144594/181818982-4deb5b5f-7e51-41aa-b3cf-edc7dcf5cd0b.png)

Next, click the pencil to edit the file in the top right-hand corner.
![image](https://user-images.githubusercontent.com/35144594/181818887-f2045217-be64-4663-afd7-bdbfa08f096d.png)

Now, this is where it can get a bit confusing. In line with the "og" key under "questions", create a new dictionary object.
![image](https://user-images.githubusercontent.com/35144594/181819287-db52b4fe-70ac-498b-921d-5475be88ee4b.png)
Like this:
![image](https://user-images.githubusercontent.com/35144594/181819336-420ffc76-71cd-49de-ba7c-616dfe0b2cf6.png)

Add your questions in this part in the same style as they are in in the "og" section.

Next, add your new questions to the sources, by creating a new item in the "sources" area with the same name you used for the "questions" part. Fill in the data in the new "sources" object like so:
![image](https://user-images.githubusercontent.com/35144594/181819833-de80d294-7a6e-42e1-9855-cfe9da7c184f.png)

That is all that is *needed* to submit to the question bank, so you can add some info to the commit description and click "Commit changes"
![image](https://user-images.githubusercontent.com/35144594/181820118-be736c00-e602-4b9a-a177-d35dc40b89c0.png)

This then creates a new [pull request](https://github.com/EricAndrechek/FermiQuestions/pulls) for me to review to verify everything looks good before it is added to the live website. This allows me to screen questions and changes, and protect against abuse. In the past, the question bank was all on a large Google Sheet open for anyone to edit, but it was frequently abused and so I have opted for this more confusing for most people but easier for me to protect approach.

If you want to go a step further and help even more, you can follow the same file editing steps to modify the changelog of the readme to include the change. If not, no worries, I will go ahead and do this for you. 

Again, if any of this isn't working or is too complicated, leaving a new issue with the questions and sources would still be helpful. You are encouraged, however, to give it a try in editing the question bank, as even if it isn't done quite right, it will likely still be faster for me to fix that than to do it all myself from scratch. You also **won't** break anything, as I have to approve it before it goes live.

I hope this clears everything up, and thanks again for your contributions!
